# Generated by Django 5.1.4 on 2025-11-27 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0008_partenaire_rendezvous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partenaires', to='siteweb.client'),
        ),
    ]
