# Generated by Django 5.1.4 on 2025-11-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0009_alter_partenaire_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projets/')),
            ],
        ),
    ]
