# Generated by Django 5.1.4 on 2025-12-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0012_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_commande',
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=1, editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default='000000000001'),
            preserve_default=False,
        ),
    ]
