# Generated by Django 5.1.4 on 2025-12-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0013_remove_order_date_commande_order_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='temp', editable=False, max_length=12, unique=True),
        ),
    ]
