# Generated by Django 5.1.4 on 2025-12-02 04:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0015_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteweb.client'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='service',
            field=models.CharField(choices=[('support', 'Support Client'), ('commercial', 'Commercial'), ('technique', 'Technique')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], default='en_attente', max_length=20),
        ),
    ]
