# Generated by Django 5.1.4 on 2025-12-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0016_alter_order_date_created_alter_order_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='service',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('industriel', 'Industriel'), ('gouvernemental', 'Gouvernemental'), ('autre', 'Autre')], max_length=50),
        ),
    ]
