# Generated by Django 5.1.4 on 2025-12-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0017_alter_rendezvous_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
