# Generated by Django 5.1.4 on 2025-12-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0018_commentpro'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpro',
            name='note',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
