# Generated by Django 5.1.4 on 2025-12-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0028_commentpro_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
