# Generated by Django 5.1.4 on 2025-12-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0029_message_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
